### PR TITLE
Dashboard home

### PR DESCRIPTION
**Pull request by halimahexe**
## Description
I've created a home tab for the dashboard, which contains buttons that navigate to other tabs on the dashboard.

image

## How Can This Be Tested?
Run the app and navigate to `/dashboard`. The default tab should be 'home'. Try clicking the 'profile' button and be amazed!

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings, including `` npm run build ``
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Review by oskarprzybylski23 — CHANGES_REQUESTED** [review]
Could you please change value to ``profile `` for the tabs trigger to direct to a correct section

```
			<TabsContent value='my_profile'>
				<div className='min-h-screen'>
					<MyProfile userId={userId}></MyProfile>
				</div>
			</TabsContent>
```

**Review by oskarprzybylski23 — COMMENTED** [review]
Some quotes go outside the div as per screenshot below:

image

Consider cchanging the quote carousel container to fit, perhaps shape could be changed to more rectangular to accomodate text, while fitting better with other cards on homepage?
If that's too much work though don't worry, not a big issue.

**Comment by halimahexe** [comment]
Fixed! My Profile link also now works.
image

**Review by oskarprzybylski23 — APPROVED** [review]
Looks amazing! Thanks. Merging away

**Review by oskarprzybylski23 — CHANGES_REQUESTED** [review]
There's just a minor thing I've noticed earlier. There is a blank white bar at the bottom of the page above the footer. Could this be removed?
Thanks

**Pull request merged**
